version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - ENV=docker
      - DATABASE_URL=postgresql://postgres:secret@database-ktb-in:5432/ktb-in-scrape
    depends_on:
      - database

    database:
      image: "postgres"
      container_name: "database-ktb-in"
      ports:
       - "5432:5432"
      environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=ktb-in-scrape"
      # defaults the user to "postgres"
volumes:
  pg-data:

    

